GharBhada/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
   
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app1/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',views.Home,name='Home'),
    path('rentlist/',views.rentlist,name="find rent"),
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('contact',views.contactus,name='contact'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',views.userlogout,name='logout'),
     path('changepass',views.changepassword,name='changepass'),
    #path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    #path('login/',views.userlogin,name='login'),   
] 

app1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(blank=True,upload_to='images') 
    BedNum = models.IntegerField(default='1')
    HallNum = models.IntegerField(default='1')
    kitchenNum = models.IntegerField(default='1')
    Location = models.CharField(default=' ',max_length=50)
    
    Contactno = models.IntegerField(default='0')
    RentCost = models.IntegerField(default='0')
    #Facility = models.CharField(blank=True,max_length=200)
   
    
#https://www.gharjagganepal.com/properties/5406-House-Aagaman-Tole-Ward-no-13-Chandragiri-Municipality-Kathmandu-Bagmati-Nepal/?fbclid=IwAR2ne1--r3SekQXZccvNY2cqRVSLoN18ywJLiK22FfGLWeZ1Ve9EZsW0fDI

app1/forms.py
from django import forms
from app1.models import Profile
#from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password', widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email']   
        labels = {'email':'Email'} 


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['Contactno','image','HallNum','BedNum','kitchenNum','Location','RentCost']
        labels = {'Contactno':'Contact no.','HallNum':'Living Room','RentCost':'Rent Cost','BedNum':'Bed Room','kitchenNum':'Kitchen'} 
'''
    def clean(self):
        cleaned_data = super().clean()    
        valcontact = self.cleaned_data['Contactno']
        valbedno = self.cleaned_data['']
        if len(valcontact) != 10:
            raise forms.ValidationError('Contact Number must be equal to 10')
        if len(valbedno) > 2:
            raise forms.ValidationError('Bed Number must be equal to 100')
'''

app1/views.py
from django.shortcuts import render,redirect
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from app1.models import Profile

#from .forms import SignupForm,EditForm,UserDetail

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages 

from django.contrib.auth.models import User



def Home(request):
    return render(request,'home.html')


def rentlist(request):
    users = User.objects.all().select_related('profile')
    return render(request, 'rentlist.html',{'users':users})

def signup(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            #username = form.cleaned_data.get('username')
            return redirect('/login')
    else:
        form = UserRegisterForm()
    return render(request,'signup.html',{'form':form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'profile.html', context)   


def contactus(request):
    return render(request,'contact.html')  



def changepassword(request):
    pass

def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/login')   

'''
def userlogin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request,data=request.POST)
            if form.is_valid():
                uname = form.cleaned_data['username']
                upass = form.cleaned_data['password']
                user = authenticate(username=uname,password=upass)
                if user is not None:
                    login(request,user)
                    return HttpResponseRedirect('/profile')
        else:
            form =  AuthenticationForm()
        return render(request,'userlogin.html',{'form':form})
    else:
        return HttpResponseRedirect('/profile') 


@login_required
def userprofile(request):
    
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = EditForm(request.POST,instance=request.user)
            forms = UserDetail(request.POST,instance=request.user.profile)

            if  form.is_valid() and forms.is_valid(): 
                form.save()
                forms.save() 
                return redirect('/profile')   
        
        else:
            form = EditForm(instance=request.user)
            forms = UserDetail(instance=request.user.profile)

        return render(request,'profile.html',{'form':form,'forms':forms})
    else:
        return HttpResponseRedirect('/login')  

def userlogout(request):
    logout(request)
    return HttpResponseRedirect('/login')   


     CTRL + F5  
'''

templates/contact.html
<!doctype html>
<html lang="en">
{%load static%}
<html>

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/contact.css' %}"/>
    <title>Contact</title>

</head>

<body>

   <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    --> 


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">घर भाडा</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="\">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="\rentlist">Find Rent</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="\profile">Give Rent</a>
      </li>
      
       <li class="nav-item">
        <a class="nav-link" href="\contact">Contact Us</a>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Our Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>    
<br>
<p> Welcome to Contact Page!!! </p>



<div class='container-fluid'>

 
<img src="{% static "images/saroj.jpg" height="20" width="20" %}" class="rounded-circle" width="150">
<h4>Saroj Sharma</h4>
<p class="text-secondary mb-1">Developer</p>
<p class="text-muted font-size-sm">Waling, Syangja</p>


</div>

<!-- 

<br><br><br>

<h3> unordered list </h3>
<ul type='circle'>                     
<li> list1 </li>
<li> list2 </li>
<li> list3 </li>
</ul>

<h3> ordered list </h3>
<ol type='A'>                     
<li> list1 

<ul type='i'>
<li>innerlist1</li>
<li>innerlist2</li>
</ul>

</li>

<li> list2 </li>
<li> list3 </li>
</ol>

<iframe src="https://www.facebook.com/saroj.s.pangeni"> height="300" width="200"</iframe>

<table>

<tr>
<th> first name </th>
<th> last name </th>
<th> Contact no. </th>
</tr>

<tr>
<td> Saroj </td>
<td> Sharma </td>
<td> 9803125357 </td>
</tr>

</table>



<div class="container">
  <div class="row">
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
    <div class="col-sm">
      One of three columns
    </div>
  </div>
</div>

-->
</body>

</html>

templates/profile.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}"/>
    <title>Rent list</title>
</head>


<body>

  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">घर भाडा</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="\">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="\rentlist">Find Rent</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="\profile">Give Rent</a>
      </li>
      
       <li class="nav-item">
        <a class="nav-link" href="\contact">Contact Us</a>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Our Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
       <a class="btn btn-outline-primary" href="/logout/">Logout</a>
    </form>
  </div>
  </nav>

<div class="alert alert-primary alert-dismissible fade show" role="alert">
   Welcome to your Profile Page !!!!!!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="container-fluid bg">
<div id="loga">

<br>
      <form action="" method="POST" enctype="multipart/form-data">
       
       <input type="hidden" name="csrfmiddlewaretoken" value="9O3IEhyTMmtkSPSy4fYieVP6pQYSLMS4DyETtRTlS7vGTzAtD8k1xt0om56SvakB">
       {% csrf_token %}

        <img src="{% static "images/om.png" height="20" width="20" %}" class="rounded-circle" width='100' height='100'>
        <p><label for="id_username">Username:</label> <input type="text" class='form-control' name="username" value="{{user.username}}" maxlength="150" required="" id="id_username"></p>
        <p><label for="id_email">Email:</label> <input type="email" class='form-control' name="email" value="{{user.email}}" required="" id="id_email"></p>
        <p><label for="id_Contactno">Contact no.</label> <input type="number" class='form-control' name="Contactno" value="{{user.profile.Contactno}}" required="" id="id_Contactno"></p>
        
         {% if user.profile.image %} 
          <img src="{{user.profile.image.url}}" class="img-fluid" alt="Responsive image" height=500 width=500><br>  
         {% else %}
          <h1> No Image </h1>
         {% endif %}

         <p><label for="id_image">Image:</label> <input type="file" class='form-control' name="image" accept="image/*" id="id_image"></p>
         <p><label for="id_HallNum">Living Room:</label> <input type="number" class='form-control' name="HallNum" value="{{user.profile.HallNum}}" required="" id="id_HallNum"></p>
         <p><label for="id_BedNum">Bed Room:</label> <input type="number" class='form-control' name="BedNum" value="{{user.profile.BedNum}}" required="" id="id_BedNum"></p>
         <p><label for="id_kitchenNum">Kitchen:</label> <input type="number" class='form-control' name="kitchenNum" value="{{user.profile.kitchenNum}}" required="" id="id_kitchenNum"></p>
         <p><label for="id_Location">Location:</label> <input type="text" class='form-control' name="Location" value="{{user.profile.Location}}" maxlength="50" required="" id="id_Location"></p>
         <p><label for="id_RentCost">Rent Cost:</label> <input type="number" class='form-control' name="RentCost" value="{{user.profile.RentCost}}" required="" id="id_RentCost"></p>
         <input class="btn btn-primary" type="submit" value="Update">
      </form>

</div>
<div>

</body>

</html>

templates/signup.html
<!doctype html>
{% load static %}
<html lang="en">


<head>
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}" />
    

    <title>Sign UP</title>

</head>


<body>
  <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    --> 

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">घर भाडा</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="\">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="\rentlist">Find Rent</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="\profile">Give Rent</a>
      </li>
      
       <li class="nav-item">
        <a class="nav-link" href="\contact">Contact Us</a>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Our Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>







<div class='container-fluid bg' >
  <div class='row'>
    <div class='col-md-4 col-sm-4 col-xs-12'></div>
    <div class='col-md-4 col-sm-4 col-xs-12'>

<form action="" method="POST" novalidate="" enctype="multipart/form-data" id="log">
<h5>SignUp</h5><br>
<div class='form-group'>
 
<input type="hidden" name="csrfmiddlewaretoken" value="9LjGkfBzJmMOV2RmU93XeJnbfElcTQFy5G4ahl5MkVYO5RmECRvTCMlvQAdXV7us">
{% csrf_token %}

  <label for="id_username">Username:</label><input type="text" class='form-control' name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="username"><br>

  <label for="id_email">Email:</label><input type="email" class='form-control' name="email" maxlength="254" id="id_email" placeholder="email"><br>

  <label for="id_password1">Password:</label><input type="password" class='form-control' name="password1" autocomplete="new-password" required="" id="id_password1" placeholder="password"><br>

  <label for="id_password2">Confirm Password:</label><input type="password" class='form-control' name="password2" required="" id="id_password2" placeholder="confirm password"><br>


<input type="submit" value="Submit">
<a  href="{% url 'login' %}">Login</a>
</div>
</form>




</div>
</div>
           
</body>

</html>

templates/userlogin.html
<!DOCTYPE html>
<html>

<head>

<title>user login</title>

<style>
.err{
  color:red;
}
</style>

</head>


<body>
<br>
<a href="/">Home</a>
<a href="rentlist">Find Rent</a>
<a href="login">Give Rent</a>
<a href="contact">Contact us</a>
<br><br><br>

<h>Login</h><br><br>
<form action="" method="POST" novalidate>
{% csrf_token %}

<br>
{% for fm in form %}
  {{fm.label_tag}}{{fm}}{{fm.errors|striptags}}<br><br>
{% endfor %}

{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
 <p class='err'> {{error}} </p>
  {% endfor %}
{% endif %}

<input type='submit' value='Submit'>
</form>
<a href="{% url 'signup' %}">signup </a>
</body>

</html>